/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 police_car.glb 
Author: Mateusz Woliński (https://sketchfab.com/jeandiz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/police-car-9166b13b6ae341f4bfc093edb71d74f4
Title: Police car
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function PoliceModel(props) {
  const { scene } = useGLTF('/models/service/police_car.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <primitive object={nodes.Car_Rig_rootJoint} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/service/police_car.glb')
